services:
  logporter:
    image: lifailon/logporter:latest
    container_name: logporter
    restart: always
    # ports:
    #   - 9333:9333
    environment:
      - DOCKER_METRICS_PORT=9333
      - DOCKER_METRICS_HOSTNAME=
      - DOCKER_METRICS_CACHE=15 # 15s
      - DOCKER_METRICS_LOG=true
      - DOCKER_METRICS_LOG_CACHE= 15 # 15s
      - DOCKER_METRICS_VOLUME=true
      - DOCKER_METRICS_VOLUME_CACHE=15 # 15m
      # Optional: Use a docker proxy instead of the docker socket mount for improved security.
      # - DOCKER_HOST=tcp://docker-proxy:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # Optional: A docker proxy service is only needed if DOCKER_HOST is set.
  # It improves security by filtering api calls and disallowing write operations.
  # docker-proxy:
  #   image: lscr.io/linuxserver/socket-proxy:latest
  #   container_name: docker-proxy
  #   restart: always
  #   environment:
  #     - CONTAINERS=1
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    # ports:
    #   - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert-rules.yml:/etc/prometheus/alert.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/var/lib/grafana/dashboards
      - ./grafana/provider.yaml:/etc/grafana/provisioning/dashboards/provider.yaml
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: always
    # ports:
    #   - 9093:9093
    # environment:
    #   - HTTPS_PROXY=http://192.168.3.100:10808
    #   - NO_PROXY=localhost,127.0.0.1,192.168.3.0/24
    volumes:
      - ./prometheus/alert-config.yml:/etc/alertmanager/config.yml

volumes:
  prometheus_data:
  grafana_data: