name: AI

on:
  workflow_dispatch:
    inputs:
      Prompt:
        description: "Prompt for code review"
        required: true
        default: "Внимательно проанализируй код и текущие тесты, напиши новые тесты, проверь их работоспособность и сравни процент покрытия до и после"
      PR:
        description: "Create PR"
        default: false
        type: boolean
      Branch:
        description: "Branch for current or new PR"
        required: true
        default: "ops/tests"

permissions:
  contents: write
  pull-requests: write

jobs:
  opencode-review:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Install opencode
        run: curl -fsSL https://opencode.ai/install | bash

      - name: Run opencode in auto mode
        run: opencode run "${{ github.event.inputs.Prompt }}" --auto

      - name: Git diff to github summary
        run: |
          echo "## Git diff" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`diff" >> $GITHUB_STEP_SUMMARY
          git diff >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Create PR
        if: ${{ github.event.inputs.PR == 'true' }}
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: "opencode[bot] <opencode[bot]@users.noreply.github.com>"
          committer: "opencode[bot] <opencode[bot]@users.noreply.github.com>"
          commit-message: "opencode review for build ${{ github.run_number }}"
          branch: ${{ github.event.inputs.Branch }}
          title: "[AI] Code review"
          body: "Changes in code from OpenCode by prompt: ${{ github.event.inputs.Prompt }}"
          add-paths: .