name: CI

on:
  workflow_dispatch:
    inputs:
      Check:
        description: "Run container and check metrics"
        default: false
        type: boolean
      Publish:
        description: "Publish image to Docker Hub"
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build image
        run: |
          docker buildx build \
            -t lifailon/logporter:latest \
            --load .

      - name: Run logporter container
        if: ${{ github.event.inputs.Check == 'true' }}
        run: |
          docker run -d --name logporter \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -p 9333:9333 \
            --restart=always \
            lifailon/logporter:latest

      - name: Install Docker Compose
        if: ${{ github.event.inputs.Check == 'true' }}
        run: |
          mkdir -p $HOME/.local/bin
          version=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)
          curl -sSL "https://github.com/docker/compose/releases/download/$version/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          mkdir -p $HOME/.docker/cli-plugins
          cp /usr/local/bin/docker-compose $HOME/.docker/cli-plugins/docker-compose
          docker compose version

      - name: Run prometheus in compose service
        if: ${{ github.event.inputs.Check == 'true' }}
        run: |
          sed -i "s|logporter:9333|localhost:9333|" prometheus/prometheus.yml
          docker compose up -d prometheus

      - name: Check metrics
        if: ${{ github.event.inputs.Check == 'true' }}
        run: |
          curl -sS localhost:9333/metrics
          for i in {1..5}; do
            curl -sS localhost:9333/metrics | grep 'containerName="logporter"' | grep docker_cpu_usage_total
            sleep 5
          done
          docker logs logporter
          docker stop logporter && docker rm logporter

      - name: Login to Docker Hub
        if: ${{ github.event.inputs.Publish == 'true' }}
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish image to Docker Hub
        if: ${{ github.event.inputs.Publish == 'true' }}
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t lifailon/logporter:latest \
            --push .